### ISSUE TITLE
Not working with ST 3.1.1

### ISSUE THREAD

**Issue by maegul** [rinas7/StackOverflowSnippets#2]
Either no results are reported or there's an error related to showing the quick panel (see below).

Shame.  Seems unmaintained, but would be valuable if a working plugin like this existed.

`File "/Users/errollloyd/Library/Application Support/Sublime Text 3/Installed Packages/Stack Overflow Snippets.sublime-package/sosnippets/view.py", line 27, in show_quick_panel
AttributeError: 'NoneType' object has no attribute 'show_quick_panel'`
